### ISSUE TITLE
gifslice is needed to use gifview

### ISSUE THREAD

**Issue by lucasbretana** [ujjwal96/xwinwrap#9]
In the dependencies to install `gifslice` should be added so the command `gifview` can be used..

**Comment by r00tdaemon** [comment]
I think you mean gifsicle.
While gifsicle is used to run gifview it is not a dependency of Xwinwrap itself and xwinwrap can be used with a program other than gifview. For this reason I don't think it is necessary to be added as a dependency.

**Comment by lucasbretana** [comment]
Yeah.. `gifsicle` 😅 ...
But, maybe add a note in the README file where you show the command to run?..
Other than that, thanks for the app.. 🤘

**Comment by r00tdaemon** [comment]
Adding a note seems reasonable. Feel free to send a PR 🙂
